export const SAVE_MOVIES = 'SAVE_MOVIES'
export const SET_USER = 'SET_USER'
export const LOGOUT = 'LOGOUT'

export const SAVE_SEARCHED_MOVIES = 'SAVE_SEARCHED_MOVIES'
export const SAVE_SEARCHED_MOVIES_BY_GENRES = 'SAVE_SEARCHED_MOVIES_BY_GENRES'
